### PR TITLE
Bunyan support

### PR DESCRIPTION
**Pull request by jbcpollak**
Hello,

This is mostly a feeler to see what you think - I've added a bunyan stream to the project.

A few things to keep in mind:
- I didn't write any unit tests
- I used some basic ES6 syntax, so this will require Node 5.x and higher

Bunyan is great at logging metadata, but it seems like LogDNA's API doesn't really support fully generic metadata yet, so it all gets stringified into one long string. It would be nice if we could log an entire object, or an message + object.

### CODE REVIEW

**Comment by respectus** [comment]
Hi Joshua,

Thanks for writing up the Bunyan Support, I really appreciate it! I have merged your pull request and written some test cases for it. We are still deciding how exactly we want to handle the objects that are passed through our system. I will release this on github and npm soon when we make a determination. Thanks for your feedback and please let me know if you have any other concerns!

**Comment by jbcpollak** [comment]
Hi, thanks that's great! Bunyan is definitely a bit clunkier than Winston to use, but I like its API and metadata support. We've only been experimenting with LogDNA for a little while today, but I like it. We just need some way to break the messages out from the metadata cleanly.

**Comment by jbcpollak** [comment]
Hi, I was just looking into this and I wanted to say the current logdna api forces a `stringify` to happen twice, which is a performance hit. Specifically, the library will stringify objects once in `winston.js` / `bunyan.js` / or directly in `Logger.log`, and then it will be stringified again in `Logger._flush`.

To me ideally the api would let you send any number of fields to the server, and some of those fields would have special case handling (level, timestamp, message, app), and the remaining fields would be available in the UI if the user wants them.

**Comment by jbcpollak** [comment]
Sorry for the flood of commits - improved the logging format and it took a few commits to get right

**Comment by respectus** [comment]
Hi, you're right that we have two stringify calls in our node module and that this is inefficient. The stringify in the log message is a temporary solution. Currently we are restructuring our ingester system to handle objects properly. The "line" field in the message object is only accepted as a string currently by our ingester, which is why we have a stringify in the log function. Once we have fixed up our end to accept objects instead of only strings then we can remove the stringify call in this node module's log function. (We could just call stringify on our side before our ingester handles it rather than in the node module, but both are temporary solutions until we fix our ingester to handle objects).

We currently do the stringify in the flush method because we noticed higher throughput with the request module and stringified bodies rather than sending a json as the body. Either way, if we remove the stringify in the flush method and just post the json, the request module itself will stringify the json object before it posts the data. Our explicit stringify beforehand seems to have better throughput.

**Comment by jbcpollak** [comment]
OK, that sounds like what I was hoping for. I'll keep an eye out for that,
it sounds like just what we need

**Comment by jbcpollak** [comment]
Hi @respectus - I was just dusting off our logdna to try out the new features - it looks like the BunyanStream code didn't make it into master. If I update our code to match the latest release will you consider accepting a PR again?

**Comment by respectus** [comment]
Hi @jbcpollak, Thanks for keeping up with the module, we appreciate the contribution! We will gladly accept a PR for the bunyan stream, but we will be changing up things shortly. A few of our users have brought up the issue that the winston dependency unnecessarily bloats the module for non-winston users. In order to resolve this we will be creating three separate npm modules, the base logdna logger, a logdna-winston logger, and a logdna-bunyan logger. Once you have submitted the PR we will likely create a separate repo (*give you credit for spearheading the bunyan stream) and I'll go ahead and write some test cases for it too and put it up on npm. Hope this works for you, please do let me know if you have any questions or concerns, thanks!

**Pull request closed without merging**
