### PR TITLE
Clone the default headers

### PR DESCRIPTION
**Pull request by MartinRoss-IBM**
When multiple loggers are created, as the DEFAULT_REQUEST_HEADER is an object and is passed by reference, the `Authorization` header may be shared between the multiple loggers leading to logs being sent to the wrong LogDNA endpoint.

Proposed under this PR:
- Use lodash.cloneDeep to create a copy of DEFAULT_REQUEST_HEADER for each logger (deep incase this becomes nested in the future)
- Additional tests for multiple loggers. Without the fix to clone the DEFAULT_REQUEST_HEADER the `Multiple loggers retain individual apikeys` test fails on the assertion that the request headers are different (which contain the Authorization header built from of the base64 encoded apikey)
- Flush all logs after each test in `Input validation` as the `Input validation for logs` was leaving entries in the buffer that were still there when subsequent tests ran

### CODE REVIEW

**Comment by MartinRoss-IBM** [comment]
@smusali @respectus - are you happy with the proposed changes?

**Comment by smusali** [comment]
@MartinRoss-IBM, the main changes are applied to just 4 files: `lib/logger.js`, `package.json`, `test/logger.js`, and `test/testHelper.js` but it shows 10 files changed and in 6 of them there is no change - can you `git pull --rebase upstream master` where `upstream` refers to `logdna/nodejs`? 

Overall, this looks good!

Thanks in advance!

**Comment by MartinRoss-IBM** [comment]
Thank you @smusali - have reverted the line ending changes for all non *.js files

**Comment by smusali** [comment]
Thanks, @MartinRoss-IBM!

**Pull request merged**
