### PR TITLE
CircleCI Configuration

### PR DESCRIPTION
**Pull request by smusali**
This Pull Request creates automation for publishing the new version of `LogDNA NPM Package` onto `NPM`.

### CODE REVIEW

**Comment by MartinRoss-IBM** [comment]
@smusali - when this is merged will it trigger a new npm publish for a version that includes the previously merged PR: https://github.com/logdna/nodejs/pull/51

**Comment by smusali** [comment]
@MartinRoss-IBM, basically, yes! I'm waiting for getting this approved - once approved, it's gonna do our first automated `npm publish`

**Comment by respectus** [comment]
Let's get this in and published

**Comment by smusali** [comment]
@MartinRoss-IBM, done - `v3.1.0` has just been published! Thanks!

**Pull request merged**
